- https://ru.wikipedia.org/wiki/Билинейная_интерполяция

# geometry

In [45]:
import numpy as np

In [70]:
class Geom:
    def __repr__(self): return f'{np.array(self)}'

In [71]:
class Point(Geom):
    def __init__(self,x,y,z=0): self.coord = [x,y,z]
    def __array__(self): return np.array(self.coord)

print(Point(0,0))

[0 0 0]


In [86]:
class Line(Geom):
    def __init__(self,*points,**args):
        self.points = list(points)
        try: args.closed = self['closed']
        except AttributeError: self.closed = True
    def __getitem__(self,idx):
        return self.data[idx]
    def __iter__(self):
        t = [self.points[0]] if self.closed else []
        return iter(self.points+t)
    def __array__(self):
        return np.array([np.array(i) for i in self])

In [87]:
board = Line(Point(0,0),Point(2,0),Point(2,1),Point(0,1),closed=True)
print(board)
# np.array(board)

[[0 0 0]
 [2 0 0]
 [2 1 0]
 [0 1 0]
 [0 0 0]]


# plot

In [37]:
import k3d, numpy

In [38]:
plot = k3d.plot(height=300,menu_visibility=False,background_color=0x222222,grid_color=0x224444,camera_mode='orbit')

In [39]:
plot += k3d.line(np.array(board),color=0x0000FF,width=.3)

TypeError: array() missing required argument 'object' (pos 0)

In [30]:
plot.display()

Output()